#!/usr/bin/env bash

./build/src/unit_tests_dbms debug --gtest_filter="HostWithPortsTest*"
./build/src/unit_tests_dbms debug --gtest_filter="LinkedHashMapTest*"
./build/src/unit_tests_dbms debug --gtest_filter="RuntimeFilterTest*"
./build/src/unit_tests_dbms debug --gtest_filter="NodeSelectorTest*"
./build/src/unit_tests_dbms debug --gtest_filter="ExchangeQueueTest*"
./build/src/unit_tests_dbms debug --gtest_filter="RPCchannelPoolTest*"
./build/src/unit_tests_dbms debug --gtest_filter="ExchangeSourceTest*"
./build/src/unit_tests_dbms debug --gtest_filter="RangeSelectiveTest*"
./build/src/unit_tests_dbms debug --gtest_filter="RepartitionTransformTest*"
./build/src/unit_tests_dbms debug --gtest_filter="ExchangeLocalBroadcastTest*"
./build/src/unit_tests_dbms debug --gtest_filter="ExchangeSinkTest*"
./build/src/unit_tests_dbms debug --gtest_filter="ExchangeRemoteTest*"
./build/src/unit_tests_dbms debug --gtest_filter="PlanSegmentTest*"
./build/src/unit_tests_dbms debug --gtest_filter="ProtobufTest*"
./build/src/unit_tests_dbms debug --gtest_filter="PlanSegmentProcessListTest*"
./build/src/unit_tests_dbms debug --gtest_filter="ProfileLogHubTest*"
./build/src/unit_tests_dbms debug --gtest_filter="ExchangeSourceStepTest*"
./build/src/unit_tests_dbms debug --gtest_filter="SchedulerTest*"
./build/src/unit_tests_dbms trace --gtest_filter="HostWithPorts*"
./build/src/unit_tests_dbms trace --gtest_filter="LinkedHashMap*"
./build/src/unit_tests_dbms trace --gtest_filter="NameResolutionTest*"
./build/src/unit_tests_dbms trace --gtest_filter="JSONSuite*"
./build/src/unit_tests_dbms trace --gtest_filter="ASTEqualsTest*"
./build/src/unit_tests_dbms debug --gtest_filter="PlanSegmentExecutorTest*"
#./build/src/unit_tests_dbms trace --gtest_filter="*FormatHiliting*Ext*:*Parser*Ext*"
