syntax = "proto3";
package DB.Protos;

message ExchangeMode {
    enum Enum {
        UNKNOWN = 0;
        LOCAL_NO_NEED_REPARTITION = 1;  // Local table join local table
        LOCAL_MAY_NEED_REPARTITION = 2; // Local table join remote table
        REPARTITION = 3;                // Remote table join remote table
        BROADCAST = 4;
        GATHER = 5;
        BUCKET_REPARTITION = 6;
    }
}

message ReportProfileType {
    enum Enum {
      Unspecified = 0;
      QueryPlan = 1;
      QueryPipeline = 2;
    }
}

message OverflowMode {
    enum Enum {
      THROW = 0;
      BREAK = 1;
      ANY = 2;
    }
}

message TopNModel {
    enum Enum {
      ROW_NUMBER = 0;
      RANKER = 1;
      DENSE_RANK = 2;
    }
}

message TopNFilteringAlgorithm {
    enum Enum {
        Unspecified = 0;
        SortAndLimit = 1;
        Limit = 2;
        Heap = 3;
    }
}

message ASOF {
    message Inequality {
        enum Enum {
            None = 0;
            Less = 1;
            Greater = 2;
            LessOrEquals = 3;
            GreaterOrEquals = 4;
        }
    }
}

message DistributionType {
    enum Enum {
      UNKNOWN = 0;
      REPARTITION = 1;
      BROADCAST = 2;
    }
}

message JoinAlgorithm {
    enum Enum {
      AUTO = 0;
      HASH = 1;
      PARTIAL_MERGE = 2;
      PREFER_PARTIAL_MERGE = 3;
      NESTED_LOOP_JOIN = 4;
      PARALLEL_HASH = 5;
      GRACE_HASH = 6;
    }
}

message TotalsMode {
    enum Enum {
      BEFORE_HAVING = 0;
      AFTER_HAVING_INCLUSIVE = 1;
      AFTER_HAVING_EXCLUSIVE = 2;
      AFTER_HAVING_AUTO = 3;
    }
}

message IntersectExceptOperator {
  enum Enum {
    UNKNOWN = 0;
    EXCEPT_ALL = 1;
    EXCEPT_DISTINCT = 2;
    INTERSECT_ALL = 3;
    INTERSECT_DISTINCT = 4;
  }
}

message UUID {
    fixed64 low = 1;
    fixed64 high = 2;
}

message StorageID {
    string database = 1;
    string table = 2;
    UUID uuid = 3;
    string server_vw_name = 4;
}

message HostWithPorts {
    string hostname = 1;
    string host = 2;
    uint32 rpc_port = 3;
    uint32 tcp_port = 4;
    uint32 http_port = 5;
    uint32 exchange_port = 6;
    uint32 exchange_status_port = 7;
}
