syntax = "proto3";
package DB.Protos;

message ExchangeMode {
    enum Enum {
        UNKNOWN = 0;
        LOCAL_NO_NEED_REPARTITION = 1;  // Local table join local table
        LOCAL_MAY_NEED_REPARTITION = 2; // Local table join remote table
        REPARTITION = 3;                // Remote table join remote table
        BROADCAST = 4;
        GATHER = 5;
        BUCKET_REPARTITION = 6;
    }
}

message ReportProfileType {
    enum Enum {
      Unspecified = 0;
      QueryPlanExt = 1;
      QueryPipeline = 2;
    }
}

message OverflowMode {
    enum Enum {
      THROW = 0;
      BREAK = 1;
      ANY = 2;
    }
}

message SortOrder {
  enum Enum {
    ASC_NULLS_FIRST = 0;
    ASC_NULLS_LAST = 1;
    DESC_NULLS_FIRST = 2;
    DESC_NULLS_LAST = 3;
    ANY = 4;
    UNKNOWN = 5;
    ASC_ANY = 6;
    DESC_ANY = 7;
  }
}

message TopNModel {
    enum Enum {
      ROW_NUMBER = 0;
      RANKER = 1;
      DENSE_RANK = 2;
    }
}

message TopNFilteringAlgorithm {
    enum Enum {
        Unspecified = 0;
        SortAndLimit = 1;
        Limit = 2;
        Heap = 3;
    }
}

message JoinStrictness {
enum Enum {
  Unspecified = 0;
  RightAny = 1;
  Any = 2;
  All = 3;
  Asof = 4;
  Semi = 5;
  Anti = 6;
}
}

message JoinKind {
enum Enum {
  Inner = 0;
  Left = 1;
  Right = 2;
  Full = 3;
  Cross = 4;
  Comma = 5;
  Paste = 6;
}
}

message ASOFJoinInequality {
    enum Enum {
        None = 0;
        Less = 1;
        Greater = 2;
        LessOrEquals = 3;
        GreaterOrEquals = 4;
    }
}

message DistributionType {
    enum Enum {
      UNKNOWN = 0;
      REPARTITION = 1;
      BROADCAST = 2;
    }
}

message JoinAlgorithm {
    enum Enum {
      DEFAULT = 0;
      AUTO = 1;
      HASH = 2;
      PARTIAL_MERGE = 3;
      PREFER_PARTIAL_MERGE = 4;
      PARALLEL_HASH = 5;
      GRACE_HASH = 6;
      DIRECT = 7;
      FULL_SORTING_MERGE = 8;
    }
}

message TotalsMode {
    enum Enum {
      BEFORE_HAVING = 0;
      AFTER_HAVING_INCLUSIVE = 1;
      AFTER_HAVING_EXCLUSIVE = 2;
      AFTER_HAVING_AUTO = 3;
    }
}

message IntersectExceptOperator {
  enum Enum {
    UNKNOWN = 0;
    EXCEPT_ALL = 1;
    EXCEPT_DISTINCT = 2;
    INTERSECT_ALL = 3;
    INTERSECT_DISTINCT = 4;
  }
}

message UUID {
    fixed64 low = 1;
    fixed64 high = 2;
}

message StorageID {
    string database = 1;
    string table = 2;
    UUID uuid = 3;
    string server_vw_name = 4;
}

message HostWithPorts {
    string hostname = 1;
    string host = 2;
    uint32 rpc_port = 3;
    uint32 tcp_port = 4;
    uint32 http_port = 5;
}

message WorkerNodeResourceData {
    HostWithPorts host_ports = 1;

    // number of queries in process list.
    uint32 query_num = 2;

    double cpu_usage = 3;
    double memory_usage = 4;
    uint64 memory_available = 5;
    uint64 disk_space = 6;

    optional uint64 cpu_limit = 7;
    optional uint64 memory_limit = 8;

    optional uint32 last_update_time = 9;

    optional uint64 reserved_memory_bytes = 10;
    optional uint32 reserved_cpu_cores = 11;
    optional uint32 register_time = 12;
    optional double cpu_usage_1min = 13;
    optional double memory_usage_1min = 14;

    optional uint64 last_status_create_time = 15;
    optional double cpu_usage_10sec = 26;
}
