syntax = "proto3";
import "common.proto";
package DB.Protos;

message AddressInfo {
    string host_name = 1;
    uint32 port = 2;
    uint32 exchange_port = 3;
    bytes user = 4;
    bytes password = 5;
}

message PlanSegmentPartitionSource {
    uint64 exchange_id = 1;
    AddressInfo address = 2;
    repeated uint32 partition_ids = 3;
}

message SourceTaskFilter {
    uint32 index = 1;
    uint32 count = 2;
    repeated int64 buckets = 3;
}

message DataType {
    string name = 1;
}

message NameAndTypePair {
    string name = 1;
    DataType type = 2;
    DataType type_in_storage = 3;
    optional uint64 subcolumn_delimiter_position = 4;
}

message Block {
    bytes blob = 1;
    repeated NameAndTypePair names_and_types = 2;
}

message Field {
    message FieldType {
        enum Enum {
            Null    = 0;
            UInt64  = 1;
            Int64   = 2;
            Float64 = 3;
            UInt128 = 4;
            Int128  = 5;

            String  = 16;
            Array   = 17;
            Tuple   = 18;
            Decimal32  = 19;
            Decimal64  = 20;
            Decimal128 = 21;
            AggregateFunctionState = 22;
            Decimal256 = 23;
            UInt256 = 24;
            Int256  = 25;
            Map = 26;
            UUID = 27;
            Bool = 28;
            Object = 29;
            IPv4 = 30;
            IPv6 = 31;
            CustomType = 32;
            SketchBinary = 100;
        }
    }
    Field.FieldType.Enum type = 1;
    bytes blob = 2;
}  

message FieldVector {
    repeated Field fields = 1;
}

message IPlanSegment {
    enum Enum {
        UNKNOWN = 0;
        SOURCE = 1;
        EXCHANGE = 2;
        OUTPUT = 3;
    }
    Block header = 1;
    IPlanSegment.Enum type = 2;
    ExchangeMode.Enum exchange_mode = 3;
    uint64 exchange_id = 4;
    uint64 exchange_parallel_size = 5;
    string name = 6;
    uint64 segment_id = 7;
    repeated string shuffle_keys = 8;
}

message PlanSegmentInput {
    IPlanSegment base_plan_segment = 1;
    uint64 parallel_index = 2;
    bool keep_order = 3;
    repeated AddressInfo source_addresses = 4;
    StorageID storage_id = 5;
}
 
message PlanSegmentOutput {
    IPlanSegment base_plan_segment = 1;
    string shuffle_hash_function = 2;
    uint32 parallel_size = 3;
    bool keep_order = 4;
    FieldVector shuffle_function_parameters = 5;
}


//---------------- Query Plan --------------

message FillColumnDescription {
    Field fill_from = 1;
    Field fill_to = 2;
    Field fill_step = 3;
}

message Collator {
    string locale = 1;
}

message SortColumnDescription {
    string column_name = 1;
    uint64 column_number = 2;
    int32 direction = 3;
    int32 nulls_direction = 4;
    optional Collator collator = 5;
    bool with_fill = 6;
    FillColumnDescription fill_description = 7;
}

message SortColumnDescriptionWithColumnIndex {
    SortColumnDescription base = 1;
    uint64 column_number = 2;
}

message DataStream {
    message SortScope {
        enum Enum {
            None   = 0;
            Chunk  = 1; /// Separate chunks are sorted
            Stream = 2; /// Each data steam is sorted
            Global = 3; /// Data is globally sorted
        }
    }
    Block header = 1;
    string distinct_columns = 2;
    bool has_single_port = 3;
    repeated SortColumnDescription sort_description = 4;
    SortScope.Enum sort_scope = 5;
}

message StringVec {
    repeated string values = 1;
}

message AST {
    bytes blob = 1;     // exact binary
    string text = 2;    // only for read
}

message Partitioning {
    message Handle {
        enum Enum{
            SINGLE = 0;
            COORDINATOR = 1;
            FIXED_HASH = 2;
            FIXED_ARBITRARY = 3;
            FIXED_BROADCAST = 4;
            SCALED_WRITER = 5;
            BUCKET_TABLE = 6;
            ARBITRARY = 7;
            FIXED_PASSTHROUGH = 8;
            UNKNOWN = 9;
        }
    }
    message Component {
        enum Enum{
            ANY = 0;
            COORDINATOR = 1;
            WORKER = 2;
        }
    }
    Handle.Enum handle = 1;
    repeated string columns = 2;
    bool require_handle = 3;
    uint64 buckets = 4;
    bool enforce_round_robin = 5;
    Component.Enum component = 6;
    bool exactly_match = 7;
    AST bucket_expr = 8;
}

message SizeLimits {
    uint64 max_rows = 1;
    uint64 max_bytes = 2;
    OverflowMode.Enum overflow_mode = 3;
}

// From RuntimeFilterBuildInfos
message RuntimeFilter {
    enum Enum {
        LOCAL = 0;
        DISTRIBUTED = 1;
        UNKNOWN = 2;
    }
    uint32 id = 1;
    RuntimeFilter.Enum distribution = 2;
}

message Assignments {
    message KV {
        string key = 1;
        AST value = 2;
    }
    repeated KV pairs = 1;
}

message GroupingSetsParamsExt {
    repeated string used_key_names = 1;
    repeated uint64 used_keys = 2;
    repeated uint64 missing_keys = 3;
}

message GroupingDescription {
    repeated string argument_names = 1;
    string output_name = 2;
}

message AggregateFunction {
    string func_name = 1;
    repeated DataType arg_types = 2;
    FieldVector parameters = 3;
}

message AggregateDescription {
    AggregateFunction function = 1;
    repeated uint64 arguments = 3;
    repeated string argument_names = 4;
    string column_name = 5;
    string mask_column = 6;
}

message AggregatorParams {
    repeated string keys = 1;
    repeated AggregateDescription aggregates = 2;
    bool overflow_row = 3;
    uint64 max_rows_to_group_by = 4;
    OverflowMode.Enum group_by_overflow_mode = 5;
    uint64 group_by_two_level_threshold = 6;
    uint64 group_by_two_level_threshold_bytes = 7;
    uint64 max_bytes_before_external_group_by = 8;
    bool empty_result_for_aggregation_by_empty_set = 9;
    uint64 max_threads = 10;
    uint64 min_free_disk_space = 11;
    bool compile_aggregate_expressions = 12;
    uint64 min_count_to_compile_aggregate_expression = 13;
    uint64 max_block_size = 14;
    bool only_merge = 15;
    bool enable_prefetch = 16;
    bool optimize_group_by_constant_keys = 17;
    double min_hit_rate_to_use_consecutive_keys_optimization = 18;
}

message AggregatorExtParams {
    Block src_header = 1;
    Block intermediate_header = 2;
    repeated uint64 keys = 3;
    repeated AggregateDescription aggregates = 4;
    bool overflow_row = 5;
    uint64 max_rows_to_group_by = 6;
    OverflowMode.Enum group_by_overflow_mode = 7;
    uint64 group_by_two_level_threshold = 8;
    uint64 group_by_two_level_threshold_bytes = 9;
    uint64 max_bytes_before_external_group_by = 10;
    bool empty_result_for_aggregation_by_empty_set = 11;
    uint64 max_threads = 12;
    uint64 min_free_disk_space = 13;
    bool compile_aggregate_expressions = 14;
    uint64 min_count_to_compile_aggregate_expression = 15;
    bool enable_lc_group_by_opt = 16;
    uint64 spill_buffer_bytes_before_external_group_by = 17;
    bool enable_adaptive_spill = 18;
}

message AggregatingTransformParamsExt {
    AggregatorExtParams params = 1;
    bool final = 2;
}

message NameWithAliasPair {
    string name = 1;
    string alias = 2;
}

//---------- Query plan step ----------

message ITransformingStep {
    string step_description = 1;
    DataStream input_stream = 2;
}

message ISourceStep {
    Block output_header = 1;
}

message SetOperationStepExt {
    repeated DataStream input_streams = 1;
    DataStream output_stream = 2;
    map<string, StringVec> output_to_inputs = 3;
}

message AssignUniqueIdStepExt {
    ITransformingStep query_plan_base = 1;
    string unique_id = 2;
}

message EnforceSingleRowStepExt {
    ITransformingStep query_plan_base = 1;
}

message ExtremesStep {
    ITransformingStep query_plan_base = 1;
}

message FillingStep {
    ITransformingStep query_plan_base = 1;
    repeated SortColumnDescription sort_description = 2;
    repeated SortColumnDescription fill_description = 3;
    bool use_with_fill_by_sorting_prefix = 4;
}

message FinishSortingStepExt {
    ITransformingStep query_plan_base = 1;
    repeated SortColumnDescription prefix_description = 2;
    repeated SortColumnDescription result_description = 3;
    uint64 max_block_size = 4;
    uint64 limit = 5;
}

message LimitByStep {
    ITransformingStep query_plan_base = 1;
    uint64 group_length = 2;
    uint64 group_offset = 3;
    repeated string columns = 4;
}

message LimitStepExt {
    ITransformingStep query_plan_base = 1;
    uint64 limit = 2; // deprecated, use limit_or_var instead
    uint64 offset = 3; // deprecated, use offset_or_var instead
    bool always_read_till_end = 4;
    bool with_ties = 5;
    repeated SortColumnDescription description = 6;
    bool partial = 7;
}

message MarkDistinctStepExt {
    ITransformingStep query_plan_base = 1;
    string marker_symbol = 2;
    repeated string distinct_symbols = 3;
}

message MergingSortedStepExt {
    ITransformingStep query_plan_base = 1;
    repeated SortColumnDescription sort_description = 2;
    uint64 max_block_size = 3;
    uint64 limit = 4;
}

message OffsetStep {
    ITransformingStep query_plan_base = 1;
    uint64 offset = 2;
}

message SortingStepExt {
    message Stage {
        enum Enum {
            FULL = 0;
            MERGE = 1;
            PARTIAL = 2;
            PARTIAL_NO_MERGE = 3;
        }
    }
    ITransformingStep query_plan_base = 1;
    repeated SortColumnDescription result_description = 2;
    uint64 limit = 3; // deprecated, use limit_or_var instead
    bool partial = 4;
    repeated SortColumnDescription prefix_description = 5;
    optional Stage.Enum stage = 6;
}

message ValuesStepExt {
    ISourceStep query_plan_base = 1;
    repeated Field fields = 2;
    uint64 rows = 3;
}

message ExceptStepExt {
    SetOperationStepExt query_plan_base = 1;
    bool distinct = 2;
}

message IntersectStepExt {
    SetOperationStepExt query_plan_base = 1;
    bool distinct = 2;
}

message UnionStepExt {
    SetOperationStepExt query_plan_base = 1;
    uint64 max_threads = 2;
    bool local = 3;
}

message ExchangeStepExt {
    repeated DataStream input_streams = 1;
    ExchangeMode.Enum exchange_type = 2;
    Partitioning schema = 3;
    bool keep_order = 4;
}

message CTERefStepExt {
    ISourceStep query_plan_base = 1;
    uint32 id = 2;
    map<string, string> output_columns = 3;
    bool has_filter = 4;
}

message DistinctStepExt {
    ITransformingStep query_plan_base = 1;
    SizeLimits set_size_limits = 2;
    uint64 limit_hint = 3;
    repeated string columns = 4;
    bool pre_distinct = 5;
}

message PartialSortingStepExt {
    ITransformingStep query_plan_base = 1;
    repeated SortColumnDescription sort_description = 2;
    uint64 limit = 3;
    SizeLimits size_limits = 4;
}
 
message PartitionTopNStepExt {
    ITransformingStep query_plan_base = 1;
    repeated string partition = 2;
    repeated string order_by = 3;
    uint64 limit = 4;
    TopNModel.Enum model = 5;
}

message ReadNothingStep {
    ISourceStep query_plan_base = 1;
}

message ApplyStepExt {
    message ApplyType {
        enum Enum {
            CROSS = 0;
            LEFT = 1;
            SEMI = 2;
            ANTI = 3;
        }
    }
    message SubqueryType {
        enum Enum {
            SCALAR = 0;
            IN = 1;
            EXISTS = 2;
            QUANTIFIED_COMPARISON = 3;
        }
        }
}

message TopNFilteringStepExt {
    ITransformingStep query_plan_base = 1;
    repeated SortColumnDescription sort_description = 2;
    uint64 size = 3;
    TopNModel.Enum model = 4;
    TopNFilteringAlgorithm.Enum algorithm = 5;
}

message TableWriteStep {
    message InsertTarget {
        StorageID storage_id = 1;
        repeated NameAndTypePair columns = 2;
        AST query = 3;
    }
    message Target {
        oneof target {
            InsertTarget insert_target = 1;
        }
    }
    ITransformingStep query_plan_base = 1;
    Target target = 2;
    bool insert_select_with_profiles = 3;
    string output_affected_row_count_symbol = 4;
}

message TableFinishStep {
    ITransformingStep query_plan_base = 1;
    TableWriteStep.Target target = 2;
    string output_affected_row_count_symbol = 3;
    AST query = 4;
    bool insert_select_with_profiles = 5;
}

message OutfileWriteStep {
    message OutfileTarget {
        string request_uri = 1;
        string format = 2;
        string compression_method_str = 3;
        uint64 compression_level = 4;
    }
    ITransformingStep query_plan_base = 1;
    OutfileTarget outfile_target = 2;
}

message OutfileFinishStep {}

message FilterStepExt {
    ITransformingStep query_plan_base = 1;
    AST filter = 2;
    bool remove_filter_column = 3;
}

message ProjectionStepExt {
    ITransformingStep query_plan_base = 1;
    Assignments assignments = 2;
    map<string, DataType> name_to_type = 3;
    bool final_project = 4;
    map<string, RuntimeFilter> dynamic_filters = 5;
    bool index_project = 6;
}

message JoinStepExt {
    message RuntimeFilterBuilders {
        string key = 1;
        RuntimeFilter value = 2;
    }
    repeated DataStream input_streams = 1;
    DataStream output_stream = 2;
    string step_description = 3;
    JoinKind.Enum kind = 4;
    JoinStrictness.Enum strictness = 5;
    uint64 max_streams = 6;
    bool keep_left_read_in_order = 7;
    repeated string left_keys = 8;
    repeated string right_keys = 9;
    AST filter = 10;
    bool has_using = 11;
    bool flag_require_right_keys = 12;
    repeated bool require_right_keys = 13;
    ASOFJoinInequality.Enum asof_inequality = 14;
    DistributionType.Enum distribution_type = 15;
    JoinAlgorithm.Enum join_algorithm = 16;
    bool is_magic = 17;
    bool is_ordered = 18;
    repeated RuntimeFilterBuilders runtime_filter_builders = 19;
    repeated bool key_ids_null_safe = 25;
}

message MergeSortingStepExt {
    ITransformingStep query_plan_base = 1;
    repeated SortColumnDescription description = 2;
    uint64 max_merged_block_size = 3;
    uint64 limit = 4;
    uint64 max_bytes_before_remerge = 5;
    double remerge_lowered_memory_bytes_ratio = 6;
    uint64 max_bytes_before_external_sort = 7;
    uint64 min_free_disk_space = 8;
}

message MergingAggregatedStepExt {
    ITransformingStep query_plan_base = 1;
    repeated string keys = 2;
    repeated GroupingSetsParamsExt grouping_sets_params = 3;
    repeated GroupingDescription groupings = 4;
    AggregatorParams params = 5;
    bool memory_efficient_aggregation = 6;
    uint64 max_threads = 7;
    uint64 memory_efficient_merge_threads = 8;
    bool final = 9;
    uint64 max_block_size = 10;
    uint64 memory_bound_merging_max_block_bytes = 11;
    repeated SortColumnDescription group_by_sort_description = 12;
    bool is_order_overwritten = 13;
    DataStream.SortScope.Enum overwritten_sort_scope = 14;
    bool should_produce_results_in_order_of_bucket_number = 15;
    bool memory_bound_merging_of_aggregation_results_enabled = 16;
}

message InputOrderInfo {
    repeated SortColumnDescription sort_description_for_merging = 1;
    int32 direction = 2;
}

message AggregatingStepExt {
    ITransformingStep query_plan_base = 1;
    repeated string keys = 2;
    AggregatorExtParams params = 3;
    repeated GroupingSetsParamsExt grouping_sets_params = 4;
    bool final = 5;
    uint64 max_block_size = 6;
    uint64 merge_threads = 7;
    uint64 temporary_data_merge_threads = 8;
    bool storage_has_evenly_distributed_read = 9;
    InputOrderInfo group_by_info = 10;
    repeated SortColumnDescriptionWithColumnIndex group_by_sort_description = 11;
    repeated GroupingDescription groupings = 12;
    bool should_produce_results_in_order_of_bucket_number = 13;
    repeated string keys_not_hashed = 14;
    bool streaming_for_cache = 15; 
}

message TotalsHavingStepExt {
    ITransformingStep query_plan_base = 1;
    bool overflow_row = 2;
    AST having_filter = 3;
    string filter_column_name = 4;
    TotalsMode.Enum totals_mode = 5;
    double auto_include_threshold = 6;
    bool final = 7;
}

message ArrayJoinAction {
    repeated string columns = 1;
    bool is_left = 2;
}

message ArrayJoinStep {
    ITransformingStep query_plan_base = 1;
    ArrayJoinAction array_join = 2;
}

message CacheDependentScanInfo {
    bytes required_digest = 1;
    uint64 table_index = 2;
}
  
message TableScanCacheInfo {
    enum Status {
        CACHE_TABLE = 0;
        CACHE_DEPENDENT_TABLE = 1;
        NO_CACHE = 2;
    }
    Status status = 1;
    bytes cache_digest = 2;
    uint64 dependent_table_count = 3;
    repeated CacheDependentScanInfo cache_dependent_info = 4;
}

message SelectQueryInfo {
    AST query = 1;
    AST view_query = 2;
    AST partition_filter = 3;
    TableScanCacheInfo cache_info = 4;
    InputOrderInfo input_order_info = 5;
}
  
message TableScanStepExt {
    StorageID storage_id = 1;
    repeated NameWithAliasPair column_alias = 2;
    SelectQueryInfo query_info = 3;
    uint64 max_block_size = 4;
    AggregatingStepExt pushdown_aggregation = 5;
    ProjectionStepExt pushdown_projection = 6;
    FilterStepExt pushdown_filter = 7;
    Assignments inline_expressions = 14;
    DataStream output_stream = 15;
    DataStream table_output_stream = 16;
}

message RemoteExchangeSourceStepExt {
    DataStream input_stream = 1;
    string step_description = 2;
    repeated PlanSegmentInput inputs = 3;
    optional bool is_add_totals = 4;
    optional bool is_add_extremes = 5;
}

message FinalSampleStepExt {
    ITransformingStep query_plan_base = 1;
    uint64 sample_size = 2;
    uint64 max_chunk_size = 3;
}

message ReadStorageRowCountStepExt {
    ISourceStep query_plan_base = 1;
    AST query = 3;
    AggregateDescription agg_desc = 4;
    uint64 num_rows = 5;
    bool is_final_agg = 6;
    StorageID storage_id = 7;
}

message WindowFrame {
    message FrameType {
        enum Enum {
            ROWS = 0;
            GROUPS = 1;
            RANGE = 2;
        }
    }
    message BoundaryType {
        enum Enum {
            Unbounded = 0;
            Current = 1;
            Offset = 2;
        }
    }
    // diff bc have ExcludeType
    // enum ExcludeType {
    //    NoOthers = 0;
    //    CurrentRow = 1;
    //    Group = 2;
    //    Tie = 3;
    // }
    bool is_default = 1;
    FrameType.Enum type = 2;
    BoundaryType.Enum begin_type = 3;
    Field begin_offset = 4;
    bool begin_preceding = 5;
    BoundaryType.Enum end_type = 6;
    Field end_offset = 7;
    bool end_preceding = 8;
  }
  
message WindowFunctionDescription {
    string column_name = 1;
    AggregateFunction aggregate_function = 2;
    repeated string argument_names = 4;
}

message WindowDescription {
    string window_name = 1;
    repeated SortColumnDescription partition_by = 2;
    repeated SortColumnDescription order_by = 3;
    repeated SortColumnDescription full_sort_description = 4;
    WindowFrame frame = 5;
    repeated WindowFunctionDescription window_functions = 6;
}

message WindowStep {
    ITransformingStep query_plan_base = 1;
    WindowDescription window_description = 2;
    repeated WindowFunctionDescription window_functions = 3;
    bool streams_fan_out = 4;
}

message IntersectOrExceptStep {
    repeated DataStream input_streams = 1;
    IntersectExceptOperator.Enum current_operator = 2;
    uint64 max_threads = 3;
}

message BufferStepExt {
    ITransformingStep query_plan_base = 1;
}

message ExplainAnalyzeStepExt {}

message CacheParam {
    bytes digest = 1;
    map<uint64, uint64> output_pos_to_cache_pos = 2;
    map<uint64, uint64> cache_pos_to_output_pos = 3;
    StorageID cached_table = 4;
    repeated StorageID dependent_tables = 5;
}

message IntermediateResultCacheStepExt {
    string step_description = 1;
    DataStream input_stream = 2;
    CacheParam cache_param = 3;
    AggregatorExtParams aggregator_params = 4;
}

message LocalExchangeStepExt {
    ITransformingStep query_plan_base = 1;
    ExchangeMode.Enum exchange_type = 2;
    Partitioning schema = 3;
}

message Edge {
    uint64 from = 1;
    uint64 to = 2;
    string source = 3;
    string target = 4;
}
  
message Graph {
    repeated uint64 node = 1;
    repeated Edge edges = 2;
    AST filter = 3;
}

message SettingChange {
    string name = 1;
    Field value = 2;
}

message SettingsChanges {
    repeated SettingChange settings_changes = 1;
}

message MultiJoinStepExt {
    Graph graph = 1;
}

message SampleRatioStep {
    ITransformingStep query_plan_base = 1;
    float sample_ratio = 2;
}

message ExpandStepExt {
    ITransformingStep query_plan_base = 1;
    Assignments assignments = 2;
    map<string, DataType> name_to_type = 3;
    string group_id_symbol = 4;
    repeated uint32 group_id_value = 5;
    map<uint32, StringVec> group_id_non_null_symbol = 6;
}
  
// this must be identical to APPLY_PROTOBUF_STEP_TYPES_AND_NAMES
//    with Step/_step postfix
//    in src/QueryPlan/IQueryPlanStep.h
// due to Protobuf will generate 'oneof' EnumName
//    by converting variable underscore name to CamelCase,
// the CamelCase and underscore name must be perfectly matched
message QueryPlanStep {
    oneof step {
        AggregatingStepExt aggregating_step_ext = 1;
        ArrayJoinStep array_join_step = 2;
        AssignUniqueIdStepExt assign_unique_id_step_ext = 3;
        CTERefStepExt c_t_e_ref_step_ext = 4;  // must be perfectly matched
        DistinctStepExt distinct_step_ext = 5;
        EnforceSingleRowStepExt enforce_single_row_step_ext = 6;
        ExceptStepExt except_step_ext = 7;
        ExchangeStepExt exchange_step_ext = 8;
        ExtremesStep extremes_step = 9;
        FillingStep filling_step = 10;
        FilterStepExt filter_step_ext = 11;
        FinalSampleStepExt final_sample_step_ext = 12;
        FinishSortingStepExt finish_sorting_step_ext = 13;
        IntersectStepExt intersect_step_ext = 14;
        JoinStepExt join_step_ext = 15;
        LimitByStep limit_by_step = 16;
        LimitStepExt limit_step_ext = 17;
        MarkDistinctStepExt mark_distinct_step_ext = 18;
        MergeSortingStepExt merge_sorting_step_ext = 19;
        MergingAggregatedStepExt merging_aggregated_step_ext = 20;
        MergingSortedStepExt merging_sorted_step_ext = 21;
        OffsetStep offset_step = 22;
        PartialSortingStepExt partial_sorting_step_ext = 23;
        PartitionTopNStepExt partition_top_n_step_ext = 24;
        ProjectionStepExt projection_step_ext = 25;
        ReadNothingStep read_nothing_step = 26;
        ReadStorageRowCountStepExt read_storage_row_count_step_ext = 27;
        RemoteExchangeSourceStepExt remote_exchange_source_step_ext = 28;
        SortingStepExt sorting_step_ext = 29;
        TableFinishStep table_finish_step = 30;
        TableScanStepExt table_scan_step_ext = 31;
        TableWriteStep table_write_step = 32;
        TopNFilteringStepExt top_n_filtering_step_ext = 33;
        UnionStepExt union_step_ext = 34;
        WindowStep window_step = 35;
        ValuesStepExt values_step_ext = 36;
        IntersectOrExceptStep intersect_or_except_step = 37;
        BufferStepExt buffer_step_ext = 38;
        ApplyStepExt apply_step_ext = 39;
        OutfileWriteStep outfile_write_step = 40;
        OutfileFinishStep outfile_finish_step = 41;
        ExplainAnalyzeStepExt explain_analyze_step_ext = 44;
        TotalsHavingStepExt totals_having_step_ext = 50;
        IntermediateResultCacheStepExt intermediate_result_cache_step_ext = 53;
        LocalExchangeStepExt local_exchange_step_ext = 54;
        MultiJoinStepExt multi_join_step_ext = 55;
        SampleRatioStep sample_ratio_step = 56;
        ExpandStepExt expand_step_ext = 57;
    }
}

message QueryPlanNode {
    uint64 plan_id = 1;
    repeated uint64 children = 2;
    QueryPlanStep step = 3;
}

message QueryPlanExt {
    message PlanMode {
        enum Enum{
            TreeLike = 0;
            Flatten = 1;
        }
    }
    uint64 root_id = 1;
    map<uint64, QueryPlanNode> plan_nodes = 2;
    // CteId -> plan_id
    map<uint64, uint64> cte_id_mapping = 3;
    PlanMode.Enum mode = 4;
}
