syntax = "proto3";
import "common.proto";
import "plan_node.proto";
package DB.Protos;

message PlanSegment {
    string cluster_name = 1;
    uint32 parallel = 2;
    uint32  exchange_parallel_size = 3;
    QueryPlan query_plan = 4;
    repeated PlanSegmentOutput outputs = 5;
    repeated uint32 runtime_filter_id = 6;
    uint32 segment_id = 7;
    string query_id = 8;
    AddressInfo coordinator_address = 9;
    ReportProfileType.Enum profile_type = 10;
}

message Progress {
    // below should sync with Progress.h
    uint64 read_rows = 1;          /// Rows (source) processed.
    uint64 read_bytes = 2;         /// Bytes (uncompressed, source) processed.
    uint64 read_raw_bytes = 3;     /// Raw bytes processed.
    uint64 total_rows_to_read = 4;
    uint64 total_raw_bytes_to_read = 5;
    uint64 written_rows = 6;
    uint64 written_bytes = 7;
    uint64 written_elapsed_milliseconds = 8;
    uint64 disk_cache_read_bytes = 9;
  }
  
  message RuntimeSegmentsMetrics {
    int64 cpu_micros = 1;
    Progress progress = 2;
  }
