syntax = "proto3";

package DB.Protos;

import "common.proto";
import "plan_node.proto";

option cc_generic_services = true;

message PlanSegment {
    string cluster_name = 1;
    uint32 parallel = 2;
    uint32  exchange_parallel_size = 3;
    QueryPlanExt query_plan = 4;
    repeated PlanSegmentOutput outputs = 5;
    repeated uint32 runtime_filter_id = 6;
    uint32 segment_id = 7;
    string query_id = 8;
    AddressInfo coordinator_address = 9;
    ReportProfileType.Enum profile_type = 10;
}

message Progress {
    // below should sync with Progress.h
    uint64 read_rows = 1;           /// Rows (source) processed.
    uint64 read_bytes = 2;          /// Bytes (uncompressed, source) processed.
    uint64 total_rows_to_read = 3;
    uint64 total_bytes_to_read = 4;
    uint64 written_rows = 5;
    uint64 written_bytes = 6;
    uint64 result_rows = 7;
    uint64 result_bytes = 8;
    uint64 elapsed_ns = 9;
}

message RuntimeSegmentsMetrics {
    int64 cpu_micros = 1;
    Progress progress = 2;
}

message TraceMeta {
    string traceparent = 1;
    string tracestate = 2;
}

message QueryCommon {
    uint32 brpc_minor_revision = 1;
    string query_id = 2;
    string initial_user = 3;
    int64 initial_query_start_time = 4;
    string initial_client_host = 5;
    int32 initial_client_port = 6;  
    // related to query quota mechanism
    string quota = 7;
    // coordinator address
    AddressInfo coordinator_address = 8;
    string database = 9;
    // Opentelemetry protocol v2
    TraceMeta trace_meta = 10;
    bool check_session = 11;
    uint64 query_expiration_timestamp = 12;
    // support subquery
    string parent_query_id = 13;
    bool is_internal_query = 14;
}

message PlanSegmentRequest {
    uint32 brpc_major_revision = 1;
    uint32 query_common_buf_size = 2;
    uint32 query_settings_buf_size = 3;
    uint32 plan_segment_buf_size = 4;
    uint32 plan_segment_id = 5;
    uint32 parallel_id = 6;
    AddressInfo execution_address = 7;
    uint32 source_task_index = 8; // obosolete
    uint32 source_task_count = 9; // obosolete
    uint32 attempt_id = 10;
    SourceTaskFilter source_task_filter = 11;
    repeated PlanSegmentPartitionSource sources = 12;
    uint32 worker_epoch = 13;
}

message PlanSegmentHeader {
    uint32 plan_segment_id = 1;
    uint32 parallel_id = 2;
    uint32 plan_segment_buf_size = 3;
    uint32 attempt_id = 4;
    SourceTaskFilter source_task_filter = 5;
}

message PlanSegmentsRequest {
    uint32 brpc_major_revision = 1;
    AddressInfo execution_address = 2;
    uint32 query_common_buf_size = 3;
    uint32 query_settings_buf_size = 4;
    repeated PlanSegmentHeader headers = 5;
}

message PlanSegmentResponse {
    int32 status_code = 1;
    string message = 2;
    string address = 3;
    HostWithPorts host_ports = 4;
    string exception = 5;
}

//Cancel Query
message CancelQueryRequest {
    string query_id = 1;
    string coordinator_address = 2;
};
  
message CancelQueryResponse {
    string status_code = 1;
    string message = 2;
    string exception = 3;
};

// Report plan segment status
message SendBytesByParallelIndex {
    uint64 parallel_index = 1;
    uint64 bytes_sent = 2;
}

message SendBytes {
    uint64 exchange_id = 1;
    repeated SendBytesByParallelIndex bytes_by_index = 2;
}

message SenderMetrics {
    AddressInfo address = 1;
    repeated SendBytes send_bytes = 2;
}

message PlanSegmentStatusRequest {
    string query_id = 1;
    int32 segment_id = 2;
    bool is_succeed = 3;
    bool is_canceled = 4;
    int32 status_code = 5;
    string message = 6;
    RuntimeSegmentsMetrics metrics = 7;
    uint64 parallel_index = 8;
    SenderMetrics sender_metrics = 9;
    int32 attempt_id = 10;
}

message PlanSegmentStatusResponse {
    string query_id = 1;
    int32 status_code = 2;
    string message = 3;
    string address = 4;
}

// Report plan segment profile
message RuntimeAttributeDescription {
    string description = 1;
    repeated NameWithAliasPair details = 2;
    string additional = 3;
}

message InputProfileMetric {
    uint64 id = 1;
    uint64 input_rows = 2;
    uint64 input_bytes = 3;
    uint32 input_wait_sum_elapsed_us = 4;
    uint32 input_wait_max_elapsed_us = 5;
    uint32 input_wait_min_elapsed_us = 6;
}

message ProfileMetric {
    uint64 id = 1;
    string name = 2;
    repeated uint64 children_ids = 3;
    uint32 parallel_size = 4;
  
    uint32 sum_elapsed_us = 5;
    uint32 max_elapsed_us = 6;
    uint32 min_elapsed_us = 7;
  
    uint64 output_rows = 8;
    uint64 output_bytes = 9;
    uint32 output_wait_sum_elapsed_us = 10;
    uint32 output_wait_max_elapsed_us = 11;
    uint32 output_wait_min_elapsed_us = 12;
  
    repeated InputProfileMetric inputs = 13;
  
    map<string, RuntimeAttributeDescription> attributes = 14;
}

message PlanSegmentProfileRequest {
    string query_id = 1;
    uint32 segment_id = 2;
    bool is_succeed = 3;
    string worker_address = 4;
  
    uint64 profile_root_id = 5;
    map<uint64, ProfileMetric> profiles = 6;
  
    uint64 read_rows = 7;
    uint64 read_bytes = 8;
    uint64 total_cpu_ms = 9;
    uint64 query_duration_ms = 10;
    uint64 io_wait_ms = 11;
    string error_message = 12;
}

message PlanSegmentProfileResponse {
    string query_id = 1;
    int32 status_code = 2;
    string message = 3;
}

// execute progress and report progress profile
message ProgressRequest {
    string query_id = 1;
    uint64 segment_id = 2;
    uint64 parallel_id = 3;
    Progress progress = 4;
}

message ProgressResponse {
    int32 status_code = 1;
    string message = 2;
}

message ProcessorProfileRequest {
    uint64 event_time = 1;
    uint64 event_time_microseconds = 2;
    string query_id = 3;
    uint64 id = 4;
    uint64 parent_ids = 5;
    uint64 plan_step = 6;
    uint64 plan_group = 7;
    string processor_name = 8;
    uint32 elapsed_us = 9;
    uint32 input_wait_elapsed_us = 10;
    uint32 output_wait_elapsed_us = 11;
    uint64 input_rows = 12;
    uint64 input_bytes = 13;
    uint64 output_rows = 14;
    uint64 output_bytes = 15;
    int64 step_id = 16;
    string worker_address = 17;
}

message ProcessorsProfileRequest {
    string query_id = 1;
    repeated ProcessorProfileRequest request = 2;
}

message ProcessorProfileResponse {
    int32 status_code = 1;
    string message = 2;
}


// Log related messages
message LogEntry {
    uint64 event_time = 1;
    uint32 event_time_microseconds = 2;
    string host_name = 3;
    string query_id = 4;
    uint64 thread_id = 5;
    int32 priority = 6;
    string source = 7;
    string text = 8;
}

message SendLogsRequest {
    string query_id = 1;
    repeated LogEntry logs = 2;
    string worker_address = 3;
}

message SendLogsResponse {
    int32 status_code = 1;
    string message = 2;
}

/*
* The RPC service for query plan segment and process execution
*/
service PlanSegmentService {
    rpc executePlanSegment(PlanSegmentRequest) returns (PlanSegmentResponse);
    rpc executePlanSegments(PlanSegmentsRequest) returns (PlanSegmentResponse);
    rpc reportPlanSegmentStatus(PlanSegmentStatusRequest) returns (PlanSegmentStatusResponse);
    rpc reportPlanSegmentProfile(PlanSegmentProfileRequest) returns (PlanSegmentProfileResponse);
    rpc executeProgress(ProgressRequest) returns (ProgressResponse);
    rpc reportProcessorProfile(ProcessorProfileRequest) returns (ProcessorProfileResponse);
    rpc reportProcessorsProfile(ProcessorsProfileRequest) returns (ProcessorProfileResponse);
    rpc cancelQuery(CancelQueryRequest) returns (CancelQueryResponse);
    rpc sendLogs(SendLogsRequest) returns (SendLogsResponse);
};
