if (TARGET ch_contrib::brpc)
    add_subdirectory(Protos)
    add_subdirectory(ProtosWrapper)
endif()

#add_subdirectory(Executor)
#add_subdirectory(Analyzer)
#add_subdirectory(ProtosWrapper)
#add_subdirectory(Optimizer)
#add_subdirectory(QueryPlan)
#add_subdirectory(Runtime)
#add_subdirectory(Schedule)