#include <Query/Processors/QueryPlan/ReadFromMergeTreeExt.h>

namespace DB
{

namespace ErrorCodes
{
    extern const int INDEX_NOT_USED;
    extern const int LOGICAL_ERROR;
}

String stringToVisitorString(const String & ins)
{
    // This routine assume ins was generated by FieldVisitorToString, and should be Quoted.
    ReadBufferFromString rb(ins);
    using FieldType = String;
    FieldType res;
    readQuoted(res, rb);
    return res;
}

static MergeTreeData::DataPartsVector getSelectedPartsVector(const ReadFromMergeTree::AnalysisResult & result)
{
    MergeTreeData::DataPartsVector selected_parts_vector;
    for (auto & part_with_ranges : result.parts_with_ranges)
        selected_parts_vector.push_back(part_with_ranges.data_part);

    return selected_parts_vector;
}

static Array extractMapColumnKeys(const MergeTreeData & data, const MergeTreeData::DataPartsVector & parts)
{
    Array res;

    std::unordered_map<String, DataTypePtr> map_types;
    std::unordered_map<String, MutableColumnPtr> map_keys;
    StorageMetadataPtr metadata = data.getInMemoryMetadataPtr();
    const auto & columns = metadata->getColumns();

    for (auto it = columns.begin(); it != columns.end(); it++)
    {
        if (WhichDataType(it->type).isMap())
            map_types[it->name] = it->type;
    }

    absl::flat_hash_set<String> implicit_column_files;
    LoggerPtr logger = nullptr;
    for (auto & part : parts)
    {
        for (auto & [file, _] : part->getFilesChecksums())
        {
            if (startsWith(file, "__"))
                implicit_column_files.insert(file);
        }
    }
    

    for (const auto & file: implicit_column_files)
    {
        if (isMapBaseFile(file))
            continue;

        String map_name = parseMapNameFromImplicitFileName(file);
        if (!isMapImplicitDataFileNameNotBaseOfSpecialMapName(file, map_name))
            continue;
        String key_name = parseKeyNameFromImplicitFileName(file, map_name);

        if (!map_types.count(map_name))
        {
            if (unlikely(logger == nullptr))
                logger = getLogger(data.getLogName() + " (ExtractMapKeys)");
            LOG_WARNING(logger, "Can not find byte map column {} of implicit file {}", map_name, file);
            continue;
        }
        auto type = map_types[map_name];
        auto map_key_type = static_cast<const DataTypeMap *>(type.get())->getKeyType();
        if (!map_keys.count(map_name))
            map_keys[map_name] = IColumn::mutate(map_key_type->createColumn());

        map_keys[map_name]->insert(stringToVisitorString(key_name));
    }

    for (auto & [map_name, column] : map_keys)
    {
        auto type_it = map_types.find(map_name);
        if (type_it == map_types.end())
            throw Exception(ErrorCodes::LOGICAL_ERROR, "Can not find column {}", map_name);

        auto map_key_type = static_cast<const DataTypeMap *>(type_it->second.get())->getKeyType();
        auto serialization = map_key_type->getDefaultSerialization();

        for (size_t i = 0; i < column->size(); ++i)
        {
            WriteBufferFromOwnString buffer;
            serialization->serializeText(*column, i, buffer, {});
            res.push_back(Tuple{map_name, buffer.str()});
        }
    }

    return res;
}

ReadFromMergeTreeExt::ReadFromMergeTreeExt(
    MergeTreeData::DataPartsVector parts_,
    std::vector<AlterConversionsPtr> alter_conversions_,
    Names all_column_names_,
    const MergeTreeData & data_,
    const SelectQueryInfo & query_info_,
    const StorageSnapshotPtr & storage_snapshot_,
    const ContextPtr & context_,
    size_t max_block_size_,
    size_t num_streams_,
    std::shared_ptr<PartitionIdToMaxBlock> max_block_numbers_to_read_,
    LoggerPtr log_,
    AnalysisResultPtr analyzed_result_ptr_,
    bool enable_parallel_reading_,
    DeleteBitmapGetter delete_bitmap_getter_,
    const size_t min_block_size_,
    const bool size_predictor_estimate_lc_size_by_fullstate_,
    const bool map_column_keys_column_queried_,
    const bool sample_factor_column_queried_)
    : ReadFromMergeTree(parts_, alter_conversions_, all_column_names_, data_, query_info_, storage_snapshot, context_, max_block_size_, num_streams_, max_block_numbers_to_read_, log_, analyzed_result_ptr_, enable_parallel_reading_)
    , delete_bitmap_getter(delete_bitmap_getter_)
    , min_block_size(min_block_size_)
    , size_predictor_estimate_lc_size_by_fullstate(size_predictor_estimate_lc_size_by_fullstate_)
    , map_column_keys_column_queried(map_column_keys_column_queried_)
    , sample_factor_column_queried(sample_factor_column_queried_)
{
    if (map_column_keys_column_queried)
    {
        auto type = std::make_shared<DataTypeArray>(
            std::make_shared<DataTypeTuple>(DataTypes{std::make_shared<DataTypeString>(), std::make_shared<DataTypeString>()}));
        output_stream->header.insert({type->createColumn(), type, "_map_column_keys"});
    }
}

void ReadFromMergeTreeExt::initializePipeline(QueryPipelineBuilder & pipeline, const BuildQueryPipelineSettings & build_context)
{
    auto result = getAnalysisResult();
    LOG_DEBUG(
        log,
        "Selected {}/{} parts by partition key, {} parts by primary key, {}/{} marks by primary key, {} marks to read from {} ranges",
        result.parts_before_pk,
        result.total_parts,
        result.selected_parts,
        result.selected_marks_pk,
        result.total_marks_pk,
        result.selected_marks,
        result.selected_ranges);

    if (build_context.getBuildPipelineSettingsExt().context->getOptimizerContext()->getSettings()->report_segment_profiles)
        fillRuntimeAttributeDescriptions(result);

    auto query_id_holder = MergeTreeDataSelectExecutor::checkLimits(data, result, context);

    if (result.parts_with_ranges.empty())
    {
        pipeline.init(Pipe(std::make_shared<NullSource>(getOutputStream().header)));
        return;
    }

    auto selected_parts_vector = getSelectedPartsVector(result);

    ActionsDAGPtr result_projection;

    Names column_names_to_read = std::move(result.column_names_to_read);
    const auto & select = query_info.query->as<ASTSelectQuery &>();
    if (!select.final() && result.sampling.use_sampling &&
     !build_context.getBuildPipelineSettingsExt().context->getOptimizerContext()->getSettings()->enable_sample_by_range &&
     !build_context.getBuildPipelineSettingsExt().context->getOptimizerContext()->getSettings()->enable_deterministic_sample_by_range)
    {
        std::vector<String> add_columns = result.sampling.filter_expression->getRequiredColumns().getNames();
        column_names_to_read.insert(column_names_to_read.end(), add_columns.begin(), add_columns.end());
        std::sort(column_names_to_read.begin(), column_names_to_read.end());
        column_names_to_read.erase(std::unique(column_names_to_read.begin(), column_names_to_read.end()),
                                   column_names_to_read.end());
    }

    //todo: need projection in query_info
    const auto & input_order_info = query_info.input_order_info;
        //? query_info.input_order_info
        //: (query_info.projection ? query_info.projection->input_order_info : nullptr);

    Pipe pipe;

    const auto & settings = context->getSettingsRef();
    bool can_read_in_partition_order = false;


    if (select.final())
    {
        std::vector<String> add_columns = metadata_for_reading->getColumnsRequiredForSortingKey();
        column_names_to_read.insert(column_names_to_read.end(), add_columns.begin(), add_columns.end());

        if (!data.merging_params.sign_column.empty())
            column_names_to_read.push_back(data.merging_params.sign_column);
        if (!data.merging_params.version_column.empty())
            column_names_to_read.push_back(data.merging_params.version_column);

        std::sort(column_names_to_read.begin(), column_names_to_read.end());
        column_names_to_read.erase(std::unique(column_names_to_read.begin(), column_names_to_read.end()), column_names_to_read.end());

        pipe = spreadMarkRangesAmongStreamsFinal(
            std::move(result.parts_with_ranges),
            getNumStreams(),
            result.column_names_to_read,
            column_names_to_read,
            result_projection);
    }
    else if ((settings.optimize_read_in_order || settings.optimize_aggregation_in_order) && input_order_info)
    {
        size_t prefix_size = 0;
        //todo: need order_key_prefix_descr in query_info.input_order_info
        //size_t prefix_size = input_order_info->order_key_prefix_descr.size();
        auto order_key_prefix_ast = metadata_for_reading->getSortingKey().expression_list_ast->clone();
        order_key_prefix_ast->children.resize(prefix_size);

        auto syntax_result = TreeRewriter(context).analyze(order_key_prefix_ast, metadata_for_reading->getColumns().getAllPhysical());
        auto sorting_key_prefix_expr = ExpressionAnalyzer(order_key_prefix_ast, syntax_result, context).getActionsDAG(false);

        // todo: need partition_by_monotonicity_hint in mergetree settings 
        can_read_in_partition_order = (build_context.getBuildPipelineSettingsExt().context->getOptimizerContext()->getSettings()->optimize_read_in_partition_order ||
                                       build_context.getBuildPipelineSettingsExt().context->getOptimizerContext()->getSettings()->force_read_in_partition_order);
        //&& canReadInPartitionOrder(*metadata_for_reading, *input_order_info, query_info.query->as<ASTSelectQuery &>(),data.getSettings()->partition_by_monotonicity_hint);

        //todo: need selected_partitions in AnalysisResult
        //if (can_read_in_partition_order && result.selected_partitions > 1)
        if (can_read_in_partition_order)
        {
            /*
            pipe = spreadMarkRangesAmongStreamsWithPartitionOrder(
                std::move(result.parts_with_ranges),
                column_names_to_read,
                sorting_key_prefix_expr,
                result_projection,
                input_order_info,
                result.delayed_indices);
            */
        }
        else
        {
            pipe = spreadMarkRangesAmongStreamsWithOrder(
                std::move(result.parts_with_ranges),
                getNumStreams(),
                column_names_to_read,
                result_projection,
                input_order_info);
        }
    }

    else
    {
        pipe = spreadMarkRangesAmongStreams(
            std::move(result.parts_with_ranges),
            getNumStreams(),
            column_names_to_read);
    }

    if (build_context.getBuildPipelineSettingsExt().context->getOptimizerContext()->getSettings()->force_read_in_partition_order &&
        !can_read_in_partition_order)
        throw Exception(ErrorCodes::INDEX_NOT_USED, "Cannot read in partition order but 'force_read_in_partition_order' is set");

    if (pipe.empty())
    {
        pipeline.init(Pipe(std::make_shared<NullSource>(getOutputStream().header)));
        return;
    }

    if (result.sampling.use_sampling &&
        !build_context.getBuildPipelineSettingsExt().context->getOptimizerContext()->getSettings()->enable_sample_by_range &&
        !build_context.getBuildPipelineSettingsExt().context->getOptimizerContext()->getSettings()->enable_deterministic_sample_by_range)
    {
        auto sampling_actions = std::make_shared<ExpressionActions>(result.sampling.filter_expression);
        pipe.addSimpleTransform([&](const Block & header)
        {
            return std::make_shared<FilterTransform>(
                header,
                sampling_actions,
                result.sampling.filter_function->getColumnName(),
                false);
        });
    }


    Block cur_header = pipe.getHeader();

    auto append_actions = [&result_projection](ActionsDAGPtr actions)
    {
        if (!result_projection)
            result_projection = std::move(actions);
        else
            result_projection = ActionsDAG::merge(std::move(*result_projection), std::move(*actions));
    };


    if (sample_factor_column_queried)
    {
        ColumnWithTypeAndName column;
        column.name = "_sample_factor";
        column.type = std::make_shared<DataTypeFloat64>();
        column.column = column.type->createColumnConst(0, Field(result.sampling.used_sample_factor));

        auto adding_column = ActionsDAG::makeAddingColumnActions(std::move(column));
        append_actions(std::move(adding_column));
    }

    if (map_column_keys_column_queried)
    {
        if (build_context.getBuildPipelineSettingsExt().context->getOptimizerContext()->getSettings()->early_limit_for_map_virtual_columns > 0)
        {
            pipe.addSimpleTransform([&](const Block & header) {
                return std::make_shared<LimitTransform>(header, build_context.getBuildPipelineSettingsExt().context->getOptimizerContext()->getSettings()->early_limit_for_map_virtual_columns, 0);
            });
        }

        ColumnWithTypeAndName column;
        column.name = "_map_column_keys";
        column.type = std::make_shared<DataTypeArray>(
            std::make_shared<DataTypeTuple>(DataTypes{std::make_shared<DataTypeString>(), std::make_shared<DataTypeString>()}));

        column.column = column.type->createColumnConst(0, Field(extractMapColumnKeys(data, selected_parts_vector)));

        auto adding_column = ActionsDAG::makeAddingColumnActions(std::move(column));
        append_actions(std::move(adding_column));
    }

    if (result_projection)
        cur_header = result_projection->updateHeader(cur_header);

    if (!isCompatibleHeader(cur_header, getOutputStream().header))
    {
        auto converting = ActionsDAG::makeConvertingActions(
            cur_header.getColumnsWithTypeAndName(),
            getOutputStream().header.getColumnsWithTypeAndName(),
            ActionsDAG::MatchColumnsMode::Name);

        append_actions(std::move(converting));
    }

    if (result_projection)
    {
        auto projection_actions = std::make_shared<ExpressionActions>(result_projection);
        pipe.addSimpleTransform([&](const Block & header)
        {
            return std::make_shared<ExpressionTransform>(header, projection_actions);
        });
    }

    for (const auto & processor : pipe.getProcessors())
        processors.emplace_back(processor);

    if (query_id_holder)
        pipeline.setQueryIdHolder(std::move(query_id_holder));

    pipeline.init(std::move(pipe));
}


std::shared_ptr<IQueryPlanStep> ReadFromMergeTreeExt::copy() const
{
    throw Exception(ErrorCodes::NOT_IMPLEMENTED, "ReadFromMergeTreeExt can not copy");
}

static const char * indexTypeToString(ReadFromMergeTree::IndexType type)
{
    switch (type)
    {
        case ReadFromMergeTree::IndexType::None:
            return "None";
        case ReadFromMergeTree::IndexType::MinMax:
            return "MinMax";
        case ReadFromMergeTree::IndexType::Partition:
            return "Partition";
        case ReadFromMergeTree::IndexType::PrimaryKey:
            return "PrimaryKey";
        case ReadFromMergeTree::IndexType::Skip:
            return "Skip";
    }

    UNREACHABLE();
}

void ReadFromMergeTreeExt::fillRuntimeAttributeDescriptions(const ReadFromMergeTree::AnalysisResult & result)
{
    auto index_stats = result.index_stats;
    if (!result.index_stats.empty())
    {
        //todo:need RuntimeAttributeDescription
        //RuntimeAttributeDescription index_desc;
        for (size_t i = 0; i < index_stats.size(); ++i)
        {
            const auto & stat = index_stats[i];
            if (stat.type == IndexType::None)
                continue;
            std::stringstream out;
            out << "Type: " << indexTypeToString(stat.type) << ";";
            if (!stat.name.empty())
                out << " Name: " << stat.name << ";";
            if (!stat.description.empty())
                out << " Description: " << stat.description << ";";
            if (!stat.used_keys.empty())
            {
                String keys = fmt::format("{}", fmt::join(stat.used_keys, ","));
                out << " Keys: " << keys << ";";
            }
            if (!stat.condition.empty())
                out << " Condition: " << stat.condition << ";";
            out << " Parts: " << stat.num_parts_after;
            if (i)
                out << '/' << index_stats[i - 1].num_parts_after;
            out << ";";
            out << " Granules: " << stat.num_granules_after;
            if (i)
                out << '/' << index_stats[i - 1].num_granules_after;
            out << ";";
            //todo:need RuntimeAttributeDescription
            //index_desc.name_and_detail.emplace_back(indexTypeToString(stat.type), out.str());
        }
        //index_desc.description = "Indexes";
        //attribute_descriptions.emplace(index_desc.description, std::move(index_desc));
    }

    //todo: need RuntimeAttributeDescription
    /*
    RuntimeAttributeDescription parts_desc;
    String selected_parts_info = fmt::format(
        "Selected {}/{} parts by partition key, {} parts by primary key, {}/{} marks by primary key, {} marks to read from {} ranges",
        result.parts_before_pk,
        result.total_parts,
        result.selected_parts,
        result.selected_marks_pk,
        result.total_marks_pk,
        result.selected_marks,
        result.selected_ranges);
    parts_desc.description = selected_parts_info;
    attribute_descriptions.emplace("SelectParts", std::move(parts_desc));
    */
}

}
